[tool.djlint]
profile = "django"
indent = 2
blank_line_after_tag = ["load", "extends", "block"]
max_line_length = 120
format_js = false
format_css = false
ignore = [
  "static/**",
  "node_modules/**",
  "venv/**",
  "*/migrations/**",
]