# Generated by Django 5.2.5 on 2025-08-20 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('priority', models.DecimalField(decimal_places=1, default=0.5, help_text='Priority (0.0-1.0)', max_digits=2)),
                ('changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=20)),
                ('lastmod', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sitemap Entry',
                'verbose_name_plural': 'Sitemap Entries',
                'ordering': ['-priority', 'url'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60)),
                ('description', models.TextField(blank=True, help_text='Meta description (max 160 chars)', max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='Meta keywords', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=60)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description', max_length=160)),
                ('og_image', models.URLField(blank=True, help_text='Open Graph image URL')),
                ('og_type', models.CharField(default='website', help_text='Open Graph type', max_length=50)),
                ('twitter_card', models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter title', max_length=60)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter description', max_length=160)),
                ('twitter_image', models.URLField(blank=True, help_text='Twitter image URL')),
                ('schema_type', models.CharField(blank=True, help_text='Schema.org type', max_length=50)),
                ('schema_data', models.JSONField(blank=True, help_text='Additional schema.org data', null=True)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent indexing')),
                ('nofollow', models.BooleanField(default=False, help_text='Prevent following links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
