# Generated by Django 5.2.5 on 2025-08-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('failed_login', 'Çoklu Başarısız Giriş'), ('failed_2fa', 'Çoklu 2FA Hatası'), ('suspicious_activity', 'Şüpheli Aktivite'), ('admin_action', 'Yönetici İşlemi'), ('security_breach', 'Güvenlik İhlali')], max_length=20)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lockout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hesap Kilidi',
                'verbose_name_plural': 'Hesap Kilitleri',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('code_type', models.CharField(choices=[('2fa', 'İki Faktörlü Kimlik Doğrulama'), ('password_reset', 'Şifre Sıfırlama'), ('email_change', 'E-posta Değişikliği'), ('account_verification', 'Hesap Doğrulama')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-posta Doğrulama Kodu',
                'verbose_name_plural': 'E-posta Doğrulama Kodları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Başarılı Giriş'), ('login_failed', 'Başarısız Giriş'), ('logout', 'Çıkış'), ('password_change', 'Şifre Değişikliği'), ('email_change', 'E-posta Değişikliği'), ('2fa_enabled', '2FA Etkinleştirildi'), ('2fa_disabled', '2FA Devre Dışı Bırakıldı'), ('2fa_success', '2FA Başarılı'), ('2fa_failed', '2FA Başarısız'), ('account_locked', 'Hesap Kilitlendi'), ('account_unlocked', 'Hesap Kilidi Açıldı'), ('suspicious_activity', 'Şüpheli Aktivite'), ('password_reset_request', 'Şifre Sıfırlama İsteği'), ('password_reset_success', 'Şifre Sıfırlama Başarılı')], max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='low', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Güvenlik Logu',
                'verbose_name_plural': 'Güvenlik Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('backup_email', models.EmailField(blank=True, max_length=254)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('password_history', models.JSONField(blank=True, default=list)),
                ('login_notifications', models.BooleanField(default=True)),
                ('suspicious_activity_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Güvenlik Ayarları',
                'verbose_name_plural': 'Kullanıcı Güvenlik Ayarları',
            },
        ),
    ]
