# Generated by Django 5.2.5 on 2025-08-14 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('challenge_type', models.CharField(choices=[('math', 'Matematik İşlemi'), ('text', 'Metin Doğrulama')], default='math', max_length=10)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_solved', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CAPTCHA Meydan Okuma',
                'verbose_name_plural': 'CAPTCHA Meydan Okumaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='securitylog',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='location_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='suspicious_activity_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('multiple_failed_login', 'Çoklu Başarısız Giriş'), ('unusual_location', 'Olağandışı Konum'), ('unusual_time', 'Olağandışı Zaman'), ('multiple_devices', 'Çoklu Cihaz Kullanımı'), ('rapid_requests', 'Hızlı İstekler'), ('password_spray', 'Şifre Püskürtme'), ('credential_stuffing', 'Kimlik Bilgisi Doldurma'), ('bot_activity', 'Bot Aktivitesi'), ('unusual_user_agent', 'Olağandışı User Agent'), ('tor_usage', 'Tor Kullanımı'), ('vpn_usage', 'VPN Kullanımı')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('critical', 'Kritik')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('detected', 'Tespit Edildi'), ('investigating', 'İnceleniyor'), ('confirmed', 'Doğrulandı'), ('false_positive', 'Yanlış Pozitif'), ('resolved', 'Çözüldü')], default='detected', max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location_info', models.JSONField(blank=True, default=dict)),
                ('detection_data', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('auto_blocked', models.BooleanField(default=False)),
                ('admin_notified', models.BooleanField(default=False)),
                ('user_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Şüpheli Aktivite',
                'verbose_name_plural': 'Şüpheli Aktiviteler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='security_su_user_id_9445df_idx'), models.Index(fields=['ip_address', 'created_at'], name='security_su_ip_addr_7d4170_idx'), models.Index(fields=['severity', 'status'], name='security_su_severit_6674fb_idx')],
            },
        ),
    ]
