# Generated by Django 5.2.5 on 2025-08-14 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_captchachallenge_securitylog_device_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Başarılı Giriş'), ('login_failed', 'Başarısız Giriş'), ('logout', 'Çıkış'), ('password_change', 'Şifre Değişikliği'), ('email_change', 'E-posta Değişikliği'), ('2fa_enabled', '2FA Etkinleştirildi'), ('2fa_disabled', '2FA Devre Dışı Bırakıldı'), ('2fa_success', '2FA Başarılı'), ('2fa_failed', '2FA Başarısız'), ('account_locked', 'Hesap Kilitlendi'), ('account_unlocked', 'Hesap Kilidi Açıldı'), ('suspicious_activity', 'Şüpheli Aktivite'), ('password_reset_request', 'Şifre Sıfırlama İsteği'), ('password_reset_success', 'Şifre Sıfırlama Başarılı'), ('session_created', 'Oturum Oluşturuldu'), ('session_ended', 'Oturum Sonlandırıldı'), ('session_suspicious', 'Şüpheli Oturum'), ('all_sessions_ended', 'Tüm Oturumlar Sonlandırıldı'), ('new_device_detected', 'Yeni Cihaz Tespit Edildi'), ('device_trusted', 'Cihaz Güvenilir İşaretlendi'), ('device_suspicious', 'Cihaz Şüpheli İşaretlendi'), ('device_blocked', 'Cihaz Engellendi')], max_length=30),
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(choices=[('desktop', 'Masaüstü'), ('mobile', 'Mobil'), ('tablet', 'Tablet'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=10)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('trust_level', models.CharField(choices=[('trusted', 'Güvenilir'), ('suspicious', 'Şüpheli'), ('blocked', 'Engellenmiş'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_location', models.JSONField(blank=True, default=dict)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cihaz Bilgisi',
                'verbose_name_plural': 'Cihaz Bilgileri',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['user', 'trust_level'], name='security_de_user_id_82f002_idx'), models.Index(fields=['device_fingerprint'], name='security_de_device__e66a8c_idx'), models.Index(fields=['last_seen'], name='security_de_last_se_13aedc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=255)),
                ('session_type', models.CharField(choices=[('web', 'Web Tarayıcı'), ('mobile_app', 'Mobil Uygulama'), ('api', 'API'), ('admin', 'Yönetici Paneli')], default='web', max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('two_factor_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('login_method', models.CharField(blank=True, max_length=50)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Oturumu',
                'verbose_name_plural': 'Kullanıcı Oturumları',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='security_us_user_id_9aa362_idx'), models.Index(fields=['session_key'], name='security_us_session_cd98d8_idx'), models.Index(fields=['device_fingerprint'], name='security_us_device__92765c_idx'), models.Index(fields=['last_activity'], name='security_us_last_ac_9080e9_idx'), models.Index(fields=['is_suspicious'], name='security_us_is_susp_549551_idx')],
            },
        ),
    ]
