# Generated by Django 5.2.5 on 2025-08-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kupon Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Kupon Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('discount_type', models.CharField(choices=[('percentage', 'Yüzde İndirim'), ('fixed', 'Sabit Tutar İndirim'), ('free_shipping', 'Ücretsiz Kargo')], max_length=15, verbose_name='İndirim Türü')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İndirim Değeri')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Sipariş Tutarı')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimum İndirim Tutarı')),
                ('usage_type', models.CharField(choices=[('single', 'Tek Kullanım'), ('multiple', 'Çoklu Kullanım'), ('unlimited', 'Sınırsız Kullanım')], default='single', max_length=15, verbose_name='Kullanım Türü')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kullanım Limiti')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('valid_from', models.DateTimeField(verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateTimeField(verbose_name='Geçerlilik Bitişi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_categories', models.ManyToManyField(blank=True, to='shop.category', verbose_name='Geçerli Kategoriler')),
                ('valid_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Geçerli Kullanıcılar')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupon', verbose_name='Kullanılan Kupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='shop.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kupon Kullanımı',
                'verbose_name_plural': 'Kupon Kullanımları',
                'ordering': ['-used_at'],
            },
        ),
    ]
