# Generated by Django 5.2.5 on 2025-08-14 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_discount_amount_coupon_order_coupon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('threshold', models.PositiveIntegerField(default=1, verbose_name='Stok Eşiği')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('notified', 'Bildirim Gönderildi'), ('cancelled', 'İptal Edildi')], default='active', max_length=15, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Bildirim Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stok Uyarısı',
                'verbose_name_plural': 'Stok Uyarıları',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
