# Generated by Django 5.2.5 on 2025-08-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_options_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standart Kargo'), ('express', 'Hızlı Kargo')], default='standard', max_length=20),
        ),
    ]
