# Generated by Django 5.2.5 on 2025-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_paid_at_order_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_company_title',
            field=models.CharField(blank=True, help_text='Kurumsal için şirket ünvanı', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_name',
            field=models.CharField(blank=True, help_text='Fatura adı/soyadı veya ünvan', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_tax_office',
            field=models.CharField(blank=True, help_text='Vergi dairesi (kurumsal)', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_tckn_vkn',
            field=models.CharField(blank=True, help_text='Bireysel için TCKN (11 hane), kurumsal için VKN', max_length=11),
        ),
        migrations.AddField(
            model_name='order',
            name='e_invoice',
            field=models.BooleanField(default=False, help_text='e-Fatura mükellefi'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('bireysel', 'Bireysel'), ('kurumsal', 'Kurumsal')], default='bireysel', max_length=10),
        ),
    ]
