# Generated by Django 5.2.5 on 2025-08-16 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_billing_company_title_order_billing_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shop.order')),
            ],
            options={
                'verbose_name': 'Sipariş Durum Geçişi',
                'verbose_name_plural': 'Sipariş Durum Geçişleri',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='shop_orders_order_i_f645cf_idx')],
            },
        ),
    ]
