# Generated by Django 5.2.5 on 2025-08-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_billing_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='shop_order_invoice_idx',
        ),
    ]
