name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
      - name: Seed .env (CI)
        run: |
          cp .env.example .env || true
          echo "DEBUG=0" >> .env
          echo "SECRET_KEY=ci-secret" >> .env
          echo "ALLOWED_HOSTS=*" >> .env
          echo "SENTRY_DSN=" >> .env
      - name: Django deploy checks
        run: python manage.py check --deploy
      - name: Migrate & collectstatic
        run: |
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
      - name: Run tests
        run: python manage.py test -v 2
      - name: Audit
        run: |
          mkdir -p var/reports
          python manage.py audit --pretty --write var/reports/audit.json
      - name: Fail on audit issues
        run: |
          python - <<'PY'
          import json,sys
          data=json.load(open('var/reports/audit.json'))
          problems=0
          urls=data.get('urls',{})
          tm=data.get('templates',{})
          problems += len(urls.get('duplicates',[]))
          problems += len(tm.get('img_missing_dimensions',[]))
          problems += len(tm.get('img_missing_alt',[]))
          problems += len(tm.get('search_missing_aria',[]))
          if problems:
              print("Audit found issues:", json.dumps(data,ensure_ascii=False,indent=2))
              sys.exit(1)
          print("Audit clean.")
          PY
      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: var/reports/audit.json